### ISSUE TITLE
Keyoxidizer version isn't recognized correctly

### ISSUE THREAD

**Issue by bordam** [arch4edu/aur-auto-update#27]
Probably an issue from my side, but I don't know how to fix this. Version "v.2.4.0" isn't converted to "2.4.0" by nvchecker, causing it to flag it as outdated in the new version check

**Comment by bordam** [comment]
I checked the action and it’s still not working… do you know what’s wrong?

**Comment by petronny** [comment]
Hi, I see that keyoxidizer on AUR is at version 0.2.4 and the latest version on github is also 0.2.4.

So the bot will see that keyoxidizer is already up to date and won't do anything.

**Comment by bordam** [comment]
Hmm, ok, but I don't understand why nvchecker flags it as outdated

**Comment by petronny** [comment]
Oh, it's nvchecker you are talking about.

nvchecker compare the newly obtained version (newver) with the previously old version (oldver), not the version on AUR (and it won't know about it either). If they are not same, then nvchecker will say this package is out of date.

In this case, the oldver is `v.0.2.4` and the newver is `0.2.4`. So nvchecker will see it as an update and let the bot run the auto update script.

The auto update script will strip those non-version characters from newver and compare it to the version on AUR. Then update the version if they are different.

**Comment by bordam** [comment]
I see, thank you so much for this explanation 🙂
